### ISSUE TITLE
More universal usage examples in the README

### ISSUE THREAD

**Issue by m040601** [jschauma/xpipe#1]
First of all thank you for this tool. Ended up here following up one of those lists, https://ileriseviye.wordpress.com/2018/10/30/command-line-for-the-21-century-the-low-hanging-fruit/.

I'm not a programmer, just a proficient cli user.. And lover of these kind of "pipes" hacking. Had never heard about this tool, got really intrigued.

Then I stumbled on the first lines/paragraphs of the README, with the opening openssl example. W hich I grasped more or less to understand what the tool is for. Only much later did I find the curl/gutemberg example in the man page. Much better.  But I am still running out of ideas or inspiration on how to use it. It's certainly my fault, but I'm still hungry for examples.

Anyway just wanted to leave, an opiniated, suggestion for the README. Just some minor edits.

- Choose another opening example other than openssl.

Maybe the gutemberg. Maybe something other. As simple as possible. Without putting other specialized tools in the mix.
Something generalistic that "clicks" with everyone. Maybe even add a made up data file, example.txt with "apples" and "oranges".

- Put that opening example, and its outputt, immediately after the first sentence/paragraph. Before you proceed to detail what/why the tool does.   Put that opening example in a new "QUICKSTART" section right at the top of the man page.

- Make an additional cheat sheet with oneliners/examples or folder with examples. Or open up the wiki and let others contribute with examples.

- Put some of those oneliners in the man page.

Thanks in advance.

**Comment by jschauma** [comment]
Thanks for your report.  I've tried to clean up the language a bit in the README and added / changed some of the examples in the manual page.  Hopefully this helps make it clearer as to when one might want to use the tool.
