### ISSUE TITLE
Version 2.0 installation fails on Archlinux

### ISSUE THREAD

**Issue by m040601** [jschauma/xpipe#2]
I'm on Archlinux,

```
/usr/bin/cc is owned by gcc 12.2.0-1
Linux 5.19.8-arch1-1
```

I've been using this PKGBUILD to install, https://aur.archlinux.org/packages/xpipe-git. It was working fine before.

Since the changes introduced after 10 september 2022 with v2.0 it breaks. I can no longer . I get

```
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
cc -g -Wall -Werror -Wextra -c src/xpipe.c -o src/xpipe.o
src/xpipe.c: In function ‘getNextChunk’:
src/xpipe.c:345:23: error: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Werror=implicit-function-declaration]
  345 |                 (void)strlcpy(data, rest, dlen);
      |                       ^~~~~~~
      |                       strncpy
src/xpipe.c:402:23: error: implicit declaration of function ‘strlcat’; did you mean ‘strncat’? [-Werror=implicit-function-declaration]
  402 |                 (void)strlcat(data, line, total + bytes + 1);
      |                       ^~~~~~~
      |                       strncat
cc1: all warnings being treated as errors
make: *** [Makefile:22: src/xpipe.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: xpipe-git

```

PS: You can add to the installation section on the README page

```
If you are using Archlinux a PKGBUILD is available at https://aur.archlinux.org/packages/xpipe-git. Use your favourite AUR helper.
```

**Comment by jschauma** [comment]
somename123 ***@***.***> wrote:
> src/xpipe.c:345:23: error: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Werror=implicit-function-declaration]
>   345 |                 (void)strlcpy(data, rest, dlen);
>       |                       ^~~~~~~
>       |                       strncpy

Oooooh, ArchLinux doesn't have strlcpy(3), huh?

Gonna need to ifdef that.  Thanks for reporting!

**Comment by jschauma** [comment]
I just pushed what I hope fixes this for you.  Give it a try and let me know!

**Comment by m040601** [comment]
> xpipe(1) was developed on a NetBSD 8.0 system

Ahh ... only now did I notice that. So maybe  that explains it ...
You are using NetBSD ? Cool ! I once tinkered with FreeBSD. Now that I'm into "minimalism" again, I'm thinking about checking out NetBSD on ARM (raspberry pi etc). Not on my desktop. Dont want BSD's there.



Anyway. Please note. I am not a programmer. I have zero idea of C, makefiles etc. I am although a very proficient bash/cli/terminal user.

>   ArchLinux doesn't have strlcpy(3), huh?

No idea, only thing I can report you,

$ locate strlcpy

```
/usr/share/man/man3/OPENSSL_strlcpy.3ssl.gz
/usr/share/man/man3/strlcpy.3bsd.gz
```

$ pacman -Qo  /usr/share/man/man3/strlcpy.3bsd.gz 

```
/usr/share/man/man3/strlcpy.3bsd.gz is owned by libbsd 0.11.6-2
```

This is the libbsd officially used by Arch, https://archlinux.org/packages/extra/x86_64/libbsd/

List everything installed by libbsd, ... lotz of stuff ..

$ pacman -Ql  libbsd  | grep --color=always -i str -

```
libbsd /usr/include/bsd/bitstring.h
libbsd /usr/include/bsd/string.h
libbsd /usr/include/bsd/stringlist.h
libbsd /usr/include/bsd/sys/bitstring.h
libbsd /usr/share/man/man3/bitstr_size.3bsd.gz
libbsd /usr/share/man/man3/bitstring.3bsd.gz
libbsd /usr/share/man/man3/stringlist.3bsd.gz
libbsd /usr/share/man/man3/strlcat.3bsd.gz
libbsd /usr/share/man/man3/strlcpy.3bsd.gz
libbsd /usr/share/man/man3/strmode.3bsd.gz
libbsd /usr/share/man/man3/strnstr.3bsd.gz
libbsd /usr/share/man/man3/strnunvis.3bsd.gz
libbsd /usr/share/man/man3/strnvis.3bsd.gz
libbsd /usr/share/man/man3/strtoi.3bsd.gz
libbsd /usr/share/man/man3/strtonum.3bsd.gz
libbsd /usr/share/man/man3/strtou.3bsd.gz
libbsd /usr/share/man/man3/strunvis.3bsd.gz
libbsd /usr/share/man/man3/strvis.3bsd.gz
libbsd /usr/share/man/man3/strvisx.3bsd.gz
```

**Comment by m040601** [comment]
> I just pushed ... let me know!

Still failling,

```
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wall -Werror -Wextra -I/usr/local/include -c src/xpipe.c -o src/xpipe.o
src/xpipe.c: In function ‘replaceNum’:
src/xpipe.c:511:31: error: ‘__builtin_strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  511 |                         (void)strncat(newstr, input, strlen(input));
      |                               ^
src/xpipe.c:511:31: note: length computed here
  511 |                         (void)strncat(newstr, input, strlen(input));
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:25: src/xpipe.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: xpipe-git
```

**Comment by jschauma** [comment]
Hmm, that's a different error now.  Gonna have to see how to reproduce that...

**Comment by jschauma** [comment]
@m040601 , try once more.  If you have libbsd, then this should work now, I hope.

**Comment by m040601** [comment]
I think you nailed it and solved the problem.

I got no compilation error messages at all this time.

Tried a couple of examples, and everything seems fine.

```
fd readme.md /usr/share/doc/ | xpipe -n 10 -J % tar zcf ./archives/%.tar.gz --files-from -
```

Thanks for the quick response and awesome work.

Please keep posting more creative and inspiring uses of this tool. On the README or on a Wiki page open to all users to share examples.

**Comment by jschauma** [comment]
Right on - thanks for reporting and testing!
